config/routes.rb
Rails.application.routes.draw do
  root "users#page1"

  get "page1" => "users#page1"
  get "page2" => "users#page2"
  get "active_users" => "users#active_users"
  get "inactive_users" => "users#inactive_users"

  resources :users, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  validates :first_name, presence: true, length: { in: 2..25 }
  validates :last_name, presence: true, length: { in: 2..25 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
require "redis"

class UsersController < ApplicationController
  
  redis = Redis.new
  
  def page1
    if (User.count == 0)
      User.destroy_all
      UsersWorker.perform_async
      sleep 3
    end
    @page1 = User.all.limit(5)
  end

  def page2
    @page2 = User.all.limit(5).offset(5)
  end

  def active_users
    @active_users = User.all.where(status: "Active")
  end

  def inactive_users
    @inactive_users = User.all.where(status: "Inactive")
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InterviewTemplateRepo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/active_users.html.erb
<h1>Active Users</h1>

<table>
  <tr>
    <th>ID number</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Status</th>
    <th>Created at</th>
    <th>Email</th>
  </tr>

  <% @active_users.each do |user|%>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.status %></td>
      <td><%= user.created_at %></td>
      <td><%= user.email %></td>
    </tr>
  <% end %>
</table>

<%= button_to "Go back", page1_url, :method => :get, :class => "aButton" %>

app/views/users/inactive_users.html.erb
<h1>Inactive Users</h1>

<table>
  <tr>
    <th>ID number</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Status</th>
    <th>Created at</th>
    <th>Email</th>
  </tr>

  <% @inactive_users.each do |user|%>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.status %></td>
      <td><%= user.created_at %></td>
      <td><%= user.email %></td>
    </tr>
  <% end %>
</table>

<%= button_to "Go back", page1_url, :method => :get, :class => "aButton"%>

app/views/users/page1.html.erb
<h1>Users (Page 1)</h1>

<table>
  <tr>
    <th>ID number</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Status</th>
    <th>Created at</th>
    <th>Email</th>
  </tr>

  <% @page1.each do |user|%>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.status %></td>
      <td><%= user.created_at %></td>
      <td><%= user.email %></td>
    </tr>
  <% end %>
</table>

<div class="buttons">
<%= button_to "Page 2", page2_url, :method => :get, :class => "aButton" %>
<%= button_to "Check Active Users", active_users_url, :method => :get, :class => "aButton" %>
<%= button_to "Check Inactive Users", active_users_url, :method => :get, :class => "aButton" %>
</div>

app/views/users/page2.html.erb
<h1>Users (Page 2)</h1>

<table>
  <tr>
    <th>ID number</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Status</th>
    <th>Created at</th>
    <th>Email</th>
  </tr>

  <% @page2.each do |user|%>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.status %></td>
      <td><%= user.created_at %></td>
      <td><%= user.email %></td>
    </tr>
  <% end %>
</table>

<%= button_to "Go back", page1_url, :method => :get, :class => "aButton" %>

app/views/users/show.html.erb
<p>Hello, <%= @name %></p>